### ISSUE TITLE
Unzip Inflate Error

### ISSUE THREAD

**Issue by wjanes** [substring/fullscrape#1]
Hi 

When i start your script i get the following error:

+++ Downloading and unzipping scraper ...
ARCH = rpi2 -> the scraper (v1.0.5) will run on 4 core(s) - Downloading from https://github.com/sselph/scraper/releases/download/v1.0.5/scraper_rpi2.zip
Archive:  /tmp/scraper_rpi2.zip
  inflating: scraper
unzip: inflate error
ERROR : coulnd't unzip the scraper. Exiting ...

I am Using Recalbox Beta 17

**Comment by substring** [comment]
Hey !

can you try to start it this way : 

wget https://raw.githubusercontent.com/substring/fullscrape/master/fullscrape.sh
chmod u+x ./fullscrape.sh
./fullscrape.sh

That's how it's meant to be used. Further information on http://blog.recalbox.com/forums/topic/tuto-scraper-ses-roms-depuis-sa-recalbox-en-shell/, see english section

**Comment by wjanes** [comment]
Thanks for info

But i started it with these three commands over remote ssh.

**Comment by substring** [comment]
i just did it all over on my 3.3.0b17, had no problem. Do you have space left on / ?

**Comment by wjanes** [comment]
Hi Subs

I tried to start the file in /recalbox/share/System now, then it worked.
Thank you
