### ISSUE TITLE
Better handling of hash files

### ISSUE THREAD

**Issue by substring** [substring/fullscrape#2]
When scraping many systems, no need to download again the hash files. Do it once for the script duration for consoles, and an other time for arcade

**Comment by sselph** [comment]
Are you referring to the hash file that my scraper downloads? If so, the script should only download a new copy if the etag has changed.

You can see the logic here. The if-none-match: etag is set and if the response is Not Modified it logs it and exits the update:
https://github.com/sselph/scraper/blob/master/ds/ds.go#L143

**Comment by substring** [comment]
No, that's for my own milestones ;)
In fact, fullscrape is a script that runs on recalbox (check www.recalbox.com). It cycles through known emulators, and starts scraping using your scraper. But as i start your scraper for every system, it takes some time to check hash files, wether there are up to date or not.
What i wanna do, is make 2 dummy scrapes at the start : one for consoles, one for mame, to force a hash update, and then run the scraper with "--hash_file" to save some time
As i don't know the go language, i can't add a "--no-hash-check" or a "--just-update-hashes"

**Comment by substring** [comment]
closed by https://github.com/substring/fullscrape/commit/07ff19476526dfc5ab8546c3ea49a8f8b3481c68 despite it's not really how i wanted it
