### ISSUE TITLE
Doesn't appear to work with the latest version of recalbox?

### ISSUE THREAD

**Issue by AndyHazz** [substring/fullscrape#6]
Scraping seems to take place on 4.0.0-beta5, but no scraped data appears after a reboot.

**Comment by substring** [comment]
Hey !
Most of people who report this issue scraped using the master branch instead of the 4.0.0. Could you show me all your command lines ? From the wget to the run of the shell ? Everything is listed on the recalbox forum

**Comment by AndyHazz** [comment]
ah, yes that'd be it - I started badly with:

`wget https://raw.githubusercontent.com/substring/fullscrape/master/fullscrape.sh && chmod u+x ./fullscrape.sh`

.. I'll give the 4.0.0 branch a try later.

Can you point me at the right instructions on the forum? I was looking at this and couldn't find anything better: https://forum.recalbox.com/topic/1862/tuto-scrape-your-roms-in-shell-on-your-recalbox

**Comment by substring** [comment]
https://forum.recalbox.com/topic/1622/tuto-scraper-ses-roms-depuis-sa-recalbox-en-shell-also-in-english is the main post

**Comment by AndyHazz** [comment]
Thanks - all working well :+1: 

I also had empty gamelist.xml files in all of my rom folders which seem to be given priority over the ones fullscrape.sh creates in the system.emulationstation\gamelists\ folders - this made it look like the scrape wasn't working. After deleting those files (with emulation station closed) it's now picking up the correct scrape data.

Those empty gamelist.xml files might have been created by me running the master version of your script? Or maybe recalbox created them some other way ...
