### ISSUE TITLE
atari7800, vectrex, supergrafx can all be supported

### ISSUE THREAD

**Issue by AndyHazz** [substring/fullscrape#7]
I modified my fullscrape.sh file to include atari7800, vectrex, and supergrafx in the CANSCRAPE list, and they all scrape successfully - you should add these to your list.

**Comment by substring** [comment]
Hey thanks ! Will update that asap and close the issue accordinly !
thanks for the feedback, i hope this script helped you :smiley:

**Comment by substring** [comment]
test - on my todolist
